export const customers = [
  {
    // ID: 1,
    VisitorName: "Super Mart of the West",
    status: "check in",
    companyName: "Bentonville",
    State: "Approved",
    AddedBy: "Company",
  },
  {
    VisitorName: "Electronics Depot",
    status: "check in",
    companyName: "Atlanta",
    State: "Pending",
    AddedBy: "Company",
  },
  {
    VisitorName: "K&S Music",
    status: "check out",
    companyName: "Minnesota",
    State: "Rejected",
    AddedBy: "Company",
  },
  {
    VisitorName: "Tom's Club",
    status: "check in",
    companyName: "Issaquah",
    State: "Approved",
    AddedBy: "External",
  },
  {
    VisitorName: "E-Mart",
    status: "check out",
    companyName: "Hoffman Estates",
    State: "Pending",
    AddedBy: "Company",
  },
  {
    VisitorName: "Walters",
    status: "check out",
    companyName: "Deerfield",
    State: "Rejected",
    AddedBy: "Company",
  },
  {
    VisitorName: "StereoShack",
    status: "check in",
    companyName: "Fort Worth",
    State: "Approved",
    AddedBy: "External",
  },
  {
    VisitorName: "Circuit Town",
    status: "check out",
    companyName: "Oak Brook",
    State: "Pending",
    AddedBy: "Company",
  },
  {
    VisitorName: "Premier Buy",
    status: "------",
    companyName: "Richfield",
    State: "Rejected",
    AddedBy: "External",
  },
  {
    VisitorName: "ElectrixMax",
    status: "check in",
    companyName: "Naperville",
    State: "Approved",
    AddedBy: "Company",
  },
  {
    VisitorName: "Video Emporium",
    status: "check out",
    companyName: "Dallas",
    State: "Pending",
    AddedBy: "External",
  },
  {
    VisitorName: "Screen Shop",
    status: "check out",
    companyName: "Mooresville",
    State: "Rejected",
    AddedBy: "External",
  },
];
